#pragma once

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480

#define GRID_LINES 10
#define GRID_COLUMNS 10

#define CELL_WIDTH SCREEN_WIDTH/GRID_LINES
#define CELL_HEIGHT SCREEN_HEIGHT/GRID_COLUMNS

#define ATLAS_WIDTH 3
#define ATLAS_HEIGHT 2

#define DELTA_TIME 85

#define DIR_UP 1
#define DIR_RIGHT 2
#define DIR_DOWN 3
#define DIR_LEFT 4